# Generated by Django 5.2.17 on 2026-09-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('provider', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('funding_amount', models.CharField(blank=True, max_length=200)),
                ('is_fully_funded', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('application_instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scholarships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scholarships', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='scholarships.scholarship')),
            ],
            options={
                'db_table': 'saved_scholarships',
                'unique_together': {('user', 'scholarship')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('tracking', 'Tracking'), ('applied', 'Applied'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='tracking', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scholarship_applications',
                'unique_together': {('scholarship', 'user')},
            },
        ),
    ]
