# Generated by Django 5.2.17 on 2026-09-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_posts', models.PositiveIntegerField(default=0)),
                ('new_materials', models.PositiveIntegerField(default=0)),
                ('new_assignments', models.PositiveIntegerField(default=0)),
                ('new_listings', models.PositiveIntegerField(default=0)),
                ('new_jobs', models.PositiveIntegerField(default=0)),
                ('new_events', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('view_material', 'View Material'), ('download_material', 'Download Material'), ('submit_assignment', 'Submit Assignment'), ('post_forum', 'Post Forum'), ('join_study_group', 'Join Study Group'), ('view_job', 'View Job'), ('view_scholarship', 'View Scholarship'), ('register_event', 'Register Event'), ('send_message', 'Send Message'), ('view_course', 'View Course')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
