# Generated by Django 5.2.17 on 2026-09-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('registration', 'Registration Fee'), ('accommodation', 'Accommodation Fee'), ('caution', 'Caution Money'), ('activity', 'Activity Fee'), ('other', 'Other')], default='tuition', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('payment_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='universities.university')),
            ],
            options={
                'db_table': 'fee_structures',
                'ordering': ['-academic_year', 'fee_type'],
            },
        ),
    ]
