# Generated by Django 5.2.17 on 2026-09-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('nomination_start', models.DateTimeField()),
                ('nomination_end', models.DateTimeField()),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('results_published', 'Results Published')], default='upcoming', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='universities.university')),
            ],
            options={
                'db_table': 'elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_votes_per_voter', models.PositiveSmallIntegerField(default=1)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'db_table': 'election_positions',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.electionposition')),
            ],
            options={
                'db_table': 'candidates',
                'unique_together': {('position', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='elections.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.electionposition')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
                'unique_together': {('position', 'voter')},
            },
        ),
    ]
