# Generated by Django 5.2.17 on 2026-09-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('fake_account', 'Fake Account'), ('inappropriate_post', 'Inappropriate Post'), ('suspicious_listing', 'Suspicious Listing'), ('misleading_info', 'Misleading Information'), ('other', 'Other')], max_length=25)),
                ('content_type', models.CharField(choices=[('user', 'User'), ('forum_post', 'Forum Post'), ('comment', 'Comment'), ('marketplace_listing', 'Marketplace Listing'), ('accommodation', 'Accommodation'), ('message', 'Message'), ('club', 'Club'), ('job', 'Job'), ('other', 'Other')], default='other', max_length=25)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('content_removed', 'Content Removed'), ('suspended', 'Account Suspended'), ('banned', 'Account Banned')], default='none', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('content_removed', 'Content Removed'), ('suspended', 'Account Suspended'), ('banned', 'Account Banned')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='reports.report')),
            ],
            options={
                'db_table': 'moderation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
