# Generated by Django 5.2.17 on 2026-09-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('holiday', 'Holiday'), ('registration', 'Registration Period'), ('exam_period', 'Exam Period'), ('cat_period', 'CAT Period'), ('assignment_deadline', 'Assignment Deadline'), ('graduation', 'Graduation'), ('other', 'Other')], default='other', max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_calendar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('notes', 'Notes'), ('slides', 'Slides'), ('pdf', 'PDF'), ('tutorial', 'Tutorial'), ('past_paper', 'Past Paper'), ('revision', 'Revision Material'), ('video', 'Video'), ('link', 'External Link'), ('other', 'Other')], default='notes', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('external_url', models.URLField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
                'db_table': 'material_categories',
            },
        ),
        migrations.CreateModel(
            name='PersonalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('note', models.TextField(blank=True)),
                ('remind_at', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'personal_reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'timetables',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
