# Generated by Django 5.2.17 on 2026-09-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('announcement', 'Announcement'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('event', 'Event'), ('study_group', 'Study Group'), ('job', 'Job'), ('scholarship', 'Scholarship'), ('marketplace', 'Marketplace'), ('forum', 'Forum'), ('club', 'Club'), ('election', 'Election'), ('emergency', 'Emergency'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('assignments', models.BooleanField(default=True)),
                ('exams', models.BooleanField(default=True)),
                ('events', models.BooleanField(default=True)),
                ('study_groups', models.BooleanField(default=True)),
                ('jobs', models.BooleanField(default=True)),
                ('scholarships', models.BooleanField(default=True)),
                ('marketplace', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
